const LAST_NAMES = [
    "رضایی",
    "اختر",
    "حبیبی",
    "قربانی",
    "گرمساری",
    "خجسته",
    "صالحی فرد",
    "شعبانی",
    "توسلی",
    "فریبا",
    "حسین نژاد",
    "اکبری",
    "رجایی فرد",
    "علیدوستی",
    "کلانتری",
    "مومنی",
    "مسلمی",
    "دانشور",
    "تهرانی",
    "طباطبایی",
    "مظفری",
    "رادمهر",
    "مقدسی",
    "رامین فر",
    "کریمیان",
    "غلامی",
    "زارعی",
    "بیات",
    "خجسته",
    "صادیقیان",
    "باقر پور",
    "باباپور",
    "عباسی",
    "قربانیان",
    "کاظمی",
    "افشار",
    "میرزایی",
    "مقدم",
    "معظمی",
    "غریبی",
    "غلام پور",
    "افشان",
    "بیاتیان",
    "اولادی",
    "صادقی",
    "ارشدی",
    "یگانه",
    "عباسی فرد",
    "شیخی",
    "خلیلی",
    "اکبری",
    "آهنگران",
    "جواهریان",
    "گرشاسبی",
    "جوادی",
    "مصطفوی",
    "احمدیان",
    "خناری",
    "وفایی نژاد",
    "سلیمانی",
    "قاسمی",
    "محمدی ",
    "حسینی",
    "راد",
    "وطن دوست",
    "روحانی",
    "ایران منش",
    "کریمی",
    "عشوری",
    "علی پور",
    "ماهینی",
    "انصاری",
    "خلیل زاده",
    "محرمی",
    "مهدویان",
    "پناهیان",
    "رازقی",
    "یوسف نژاد",
    "رئیسی",
    "جهانگیر پور",
    "امینی",
    "امیریان",
    "علی نژاد",
    "نصیری",
    "کامران زاده",
    "بشیری",
    "افشار زاده",
    "میرزا پور",
    "نوروزی",
    "ترابی",
    "محسنی",
    "چاووشی",
    "بابایی",
    "اصحابی",
    "لشگری",
    "داداشی",
    "شاعری",
    "رحمتی",
    "مهرابیان",
    "احمدی",
    "رضوی",
    "حاتمی"
];

const EN_LAST_NAMES = [
    "rezaei",
    "rezaiy",
    "akhtar",
    "habibi",
    "ghorbani",
    "ghorbany",
    "garmsari",
    "khojaste",
    "khojasteh",
    "salehifard",
    "shabani",
    "tavasoli",
    "fariba",
    "hosseinnezhad",
    "akbari",
    "rajaeifard",
    "alidoosti",
    "kalantari",
    "kalantary",
    "momeni",
    "moslemi",
    "daneshvar",
    "tehrani",
    "tabatabai",
    "mozafary",
    "radmehr",
    "moghadasi",
    "raminfar",
    "karimian",
    "gholami",
    "zarei",
    "bayat",
    "khojasteh",
    "sadeghian",
    "bagherpour",
    "babapour",
    "abbasi",
    "ghorbanian",
    "kazemi",
    "afshar",
    "mirzaei",
    "moghadam",
    "moazami",
    "gharibi",
    "ghadiry",
    "gholampour",
    "afshan",
    "bayatian",
    "oladi",
    "sadeghi",
    "arshadi",
    "yeganeh",
    "abbasifard",
    "sheykhi",
    "khalili",
    "akbari",
    "ahangary",
    "javaherian",
    "garshasbi",
    "javadi",
    "mostafavi",
    "ahmadian",
    "khenari",
    "vafaeinezhad",
    "soleymani",
    "ghasemi",
    "mohammadi ",
    "hoseeini",
    "raad",
    "vatandoost",
    "roohani",
    "iranmanesh",
    "karimi",
    "ashoury",
    "alipour",
    "mahini",
    "ansari",
    "khalilzadeh",
    "moharami",
    "mahdavian",
    "panahian",
    "razeghi",
    "yousefnezhad",
    "reisi",
    "jahangirpour",
    "amini",
    "amirian",
    "alinezhad",
    "nasiri",
    "kamranzade",
    "bashiry",
    "afsharzade",
    "mirzazade",
    "norouzi",
    "torabi",
    "mohseni",
    "chavoshi",
    "babaei",
    "ashabi",
    "lashgari",
    "dadashi",
    "shaeri",
    "rahmaty",
    "mehrabian",
    "ahmadi",
    "ahmady",
    "razavi",
    "hatami",
    "hatamy"
];

module.exports = {
    LAST_NAMES,
    EN_LAST_NAMES
};
